--source: imdb.com

drop table if exists MOVIE;
drop table if exists CATEGORY;

create table CATEGORY
(
    id number(12) primary key,
    name varchar(30)
);

insert into CATEGORY(id, name) VALUES(1, 'Drama');
insert into CATEGORY(id, name) VALUES(2, 'Comedy');
insert into CATEGORY(id, name) VALUES(3, 'Family');
insert into CATEGORY(id, name) VALUES(4, 'Action');
insert into CATEGORY(id, name) VALUES(5, 'Sci-Fi');
insert into CATEGORY(id, name) VALUES(6, 'Horror');

create table MOVIE
(id       number(12) primary key,
 title    varchar2(400) not null,
 category_id number(12) ,
 year     char(4),
 plot    varchar2(4000),
 price    number(5,2),
 foreign key (category_id) references CATEGORY(id));

insert into MOVIE(id, title, category_id, year, plot, price) values(1, 'The Shawshank Redemption', 1, 1994, 'Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man''s unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.', 15);
insert into MOVIE(id, title, category_id, year, plot, price) values(2, 'The Godfather', 1, 1972, 'The Godfather "Don" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter''s wedding. Michael, Vito''s youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don''s influence for the same, Vito refuses to do it. What follows is a clash between Vito''s fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.', 17);
insert into MOVIE(id, title, category_id, year, plot, price) values(3, 'The Dark Knight', 4, 2008, 'Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as "The Joker" appears in Gotham, creating a new wave of chaos. Batman''s struggle against The Joker becomes deeply personal, forcing him to "confront everything he believes" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.', 13);
insert into MOVIE(id, title, category_id, year, plot, price) values(4, 'The Godfather: Part II', 1, 1974 ,'The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 18);
insert into MOVIE(id, title, category_id, year, plot, price) values(5, 'The Lord of the Rings: The Return of the King', 4, 2003, 'The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron''s evil army at the stone city of Minas Tirith.', 14);
insert into MOVIE(id, title, category_id, year, plot, price) values(6, 'Forrest Gump', 1, 1994, 'Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His ''mama'' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.', 12);
insert into MOVIE(id, title, category_id, year, plot, price) values(7, 'Inception', 5, 2010, 'Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb''s rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception.', 20);
insert into MOVIE(id, title, category_id, year, plot, price) values(8, 'The Matrix', 5, 1999, 'Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion.', 25);
insert into MOVIE(id, title, category_id, year, plot, price) values(9, 'Se7en', 1, 1995, 'A film about two homicide detectives'' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world''s ignorance of the Seven Deadly Sins.', 19);
insert into MOVIE(id, title, category_id, year, plot, price) values(10, 'It''s a Wonderful Life', 3, 1946, 'George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George''s modest building and loan company, which was founded by his generous father. But on Christmas Eve, George''s Uncle Billy loses the business''s $8,000 while intending to deposit it in the bank.', 14);
insert into MOVIE(id, title, category_id, year, plot, price) values(11, 'La vita è bella', 2, 1997, 'In 1930s Italy, a carefree Jewish waiter named Guido starts a fairy tale life by courting and marrying a lovely woman from a nearby city. Guido and his wife have a son and live happily together until the occupation of Italy by German forces. In an attempt to hold his family together and help his son survive the horrors of a Jewish Concentration Camp, Guido imagines that the Holocaust is a game and that the grand prize for winning is a tank.', 14);
insert into MOVIE(id, title, category_id, year, plot, price) values(12, 'The Green Mile', 1, 1999, 'Based on Stephen King''s 1996 novel of the same name. Stars Tom Hanks as a death row corrections officer during the U.S. Great Depression who witnesses supernatural events that occur after an enigmatic inmate (Michael Clarke Duncan) is brought to his facility.', 18);
insert into MOVIE(id, title, category_id, year, plot, price) values(13, 'Interstellar', 5, 2014, 'Earth''s future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind''s survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.', 22);
insert into MOVIE(id, title, category_id, year, plot, price) values(14, 'Star Wars', 4, 1977, 'The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.', 25);
insert into MOVIE(id, title, category_id, year, plot, price) values(15, 'Gisaengchung', 2, 2019, 'The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul. Without even knowing it, they, especially Mr. and Mrs. Kim, literally smell of poverty. Often as a collective, they perpetrate minor scams to get by, and even when they have jobs, they do the minimum work required.', 19);
insert into MOVIE(id, title, category_id, year, plot, price) values(16, 'Intouchables', 2, 2011, 'In Paris, the aristocratic and intellectual Philippe is a quadriplegic millionaire who is interviewing candidates for the position of his carer, with his red-haired secretary Magalie. Out of the blue, Driss cuts the line of candidates and brings a document from the Social Security and asks Phillipe to sign it to prove that he is seeking a job position so he can receive his unemployment benefit. Philippe challenges Driss, offering him a trial period of one month to gain experience helping him. Then Driss can decide whether he would like to stay with him or not. Driss accepts the challenge and moves to the mansion, changing the boring life of Phillipe and his employees.', 20);
insert into MOVIE(id, title, category_id, year, plot, price) values(17, 'Top Gun: Maverick', 4, 2022, 'After more than thirty years of service as one of the Navy''s top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.', 30);
insert into MOVIE(id, title, category_id, year, plot, price) values(18, 'WALL-E', 3, 2008, 'In a distant, but not so unrealistic, future where mankind has abandoned earth because it has become covered with trash from products sold by the powerful multi-national Buy N Large corporation, WALL-E, a garbage collecting robot has been left to clean up the mess. Mesmerized with trinkets of Earth''s history and show tunes, WALL-E is alone on Earth except for a sprightly pet cockroach. One day, EVE, a sleek (and dangerous) reconnaissance robot, is sent to Earth to find proof that life is once again sustainable. WALL-E falls in love with EVE.', 14);
insert into MOVIE(id, title, category_id, year, plot, price) values(19, 'Avengers: Infinity War', 5, 2018, 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment, the fate of Earth and existence has never been more uncertain.', 29);
insert into MOVIE(id, title, category_id, year, plot, price) values(20, 'Spider-Man: Into the Spider-Verse', 4, 2018, 'Phil Lord and Christopher Miller, the creative minds behind The Lego Movie and 21 Jump Street, bring their unique talents to a fresh vision of a different Spider-Man Universe, with a groundbreaking visual style that''s the first of its kind. "Spider-Man(TM): Into the Spider-Verse" introduces Brooklyn teen Miles Morales (Shameik Moore), and the limitless possibilities of the Spider-Verse, where more than one can wear the mask.', 23);
insert into MOVIE(id, title, category_id, year, plot, price) values(21, 'Joker', 1, 2019, 'Arthur Fleck works as a clown and is an aspiring stand-up comic. He has mental health issues, part of which involves uncontrollable laughter. Times are tough and, due to his issues and occupation, Arthur has an even worse time than most. Over time these issues bear down on him, shaping his actions, making him ultimately take on the persona he is more known as...Joker.', 19);
insert into MOVIE(id, title, category_id, year, plot, price) values(22, 'Die Hard', 4, 1988, 'NYPD cop John McClane goes on a Christmas vacation to visit his wife Holly in Los Angeles where she works for the Nakatomi Corporation. While they are at the Nakatomi headquarters for a Christmas party, a group of robbers led by Hans Gruber take control of the building and hold everyone hostage, with the exception of John, while they plan to perform a lucrative heist. Unable to escape and with no immediate police response, John is forced to take matters into his own hands.', 18);
insert into MOVIE(id, title, category_id, year, plot, price) values(23, 'Batman Begins', 4, 2005, 'When his parents are killed, billionaire playboy Bruce Wayne relocates to Asia, where he is mentored by Henri Ducard and Ra''s Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as "Batman". But it doesn''t stay quiet for long.', 21);
insert into MOVIE(id, title, category_id, year, plot, price) values(24, 'The Kid', 3, 1921, 'A woman decides to abandon her baby in the backseat of an automobile with a handwritten note attached, beseeching the finder to care for and love the child. The baby is discovered by the initially-reluctant Tramp, who eventually softens and comes to love him as his own. As the boy grows up, both he and The Tramp must learn to navigate through a life that spawns one adventure after another.', 11);
insert into MOVIE(id, title, category_id, year, plot, price) values(25, 'The Black Phone', 6, 2021, 'Finney Shaw is a shy but clever 13-year-old boy who is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of no use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer''s previous victims. And they are dead-set on making sure that what happened to them doesn''t happen to Finney.', 17);
insert into MOVIE(id, title, category_id, year, plot, price) values(26, 'Old', 6, 2021, 'This summer, visionary filmmaker M. Night Shyamalan unveils a chilling, mysterious new thriller about a family on a tropical holiday who discover that the secluded beach where they are relaxing for a few hours is somehow causing them to age rapidly - reducing their entire lives into a single day.', 18);
insert into MOVIE(id, title, category_id, year, plot, price) values(27, 'Scream', 6, 2022, 'Like the original movie 25 years ago, a cute teenage girl is at home alone when the phone rings. A man wants to play a game with her. With the threat of killing her best friend, Tara''s forced to play along. She barely survives the ghost face masked intruder''s stabbing.', 18);
insert into MOVIE(id, title, category_id, year, plot, price) values(28, 'Fresh', 6, 2022, 'The horrors of modern dating seen through one young woman''s defiant battle to survive her new boyfriend''s unusual appetites.', 16);
insert into MOVIE(id, title, category_id, year, plot, price) values(29, 'The Hunt', 6, 2020, 'Twelve strangers wake up in a clearing. They don''t know where they are -- or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted, Crystal, turns the tables on her pursuers.', 14);
insert into MOVIE(id, title, category_id, year, plot, price) values(30, '28 Days Later...', 6, 2002, 'Animal activists invade a laboratory with the intention of releasing chimpanzees that are undergoing experimentation, infected by a virus -a virus that causes rage. The naive activists ignore the pleas of a scientist to keep the cages locked, with disastrous results. Twenty-eight days later, our protagonist, Jim, wakes up from a coma, alone, in an abandoned hospital. He begins to seek out anyone else to find London is deserted, apparently without a living soul. After finding a church, which had become inhabited by zombie like humans intent on his demise, he runs for his life. Selena and Mark rescue him from the horde and bring him up to date on the mass carnage and horror as all of London tore itself apart. This is a tale of survival and ultimately, heroics, with nice subtext about mankind''s savage nature.', 13);
